const cards = [
  {
    id: 1,
    name: "Groceries",
    amount: 10,
    color: "#feba2b",
    subtext: "When you buy groceries",
  },
  {
    id: 2,
    name: "Utilities",
    amount: 20,
    color: "#03c526",
    subtext: "When you pay utilities",
  },
  {
    id: 3,
    name: "Entertainment",
    amount: 30,
    color: "#00bcfe",
    subtext: "When you go to the cinema",
  },
  {
    id: 4,
    name: "Transportation",
    amount: 40,
    color: "#ff5345",
    subtext: "When you take a bus",
  },
  {
    id: 5,
    name: "Investments",
    amount: 50,
    color: "#ff6da8",
    subtext: "When you invest",
  },
  {
    id: 6,
    name: "Groceries",
    amount: 60,
    color: "#feba2b",
    subtext: "When you buy groceries",
  },
  {
    id: 7,
    name: "Utilities",
    amount: 70,
    color: "#03c526",
    subtext: "When you pay utilities",
  },
  {
    id: 8,
    name: "Entertainment",
    amount: 80,
    color: "#00bcfe",
    subtext: "When you go to the cinema",
  },
  {
    id: 9,
    name: "Transportation",
    amount: 90,
    color: "#ff5345",
    subtext: "When you take a bus",
  },
  {
    id: 10,
    name: "Investments",
    amount: 10,
    color: "#ff6da8",
    subtext: "When you invest",
  },
  {
    id: 11,
    name: "Groceries",
    amount: 11,
    color: "#feba2b",
    subtext: "When you buy groceries",
  },
  {
    id: 12,
    name: "Utilities",
    amount: 12,
    color: "#03c526",
    subtext: "When you pay utilities",
  },
  {
    id: 13,
    name: "Entertainment",
    amount: 13,
    color: "#00bcfe",
    subtext: "When you go to the cinema",
  },
  {
    id: 14,
    name: "Transportation",
    amount: 14,
    color: "#ff5345",
    subtext: "When you take a bus",
  },
  {
    id: 15,
    name: "Investments",
    amount: 15,
    color: "#ff6da8",
    subtext: "When you invest",
  },
  {
    id: 16,
    name: "Groceries",
    amount: 16,
    color: "#feba2b",
    subtext: "When you buy groceries",
  },
  {
    id: 17,
    name: "Utilities",
    amount: 17,
    color: "#03c526",
    subtext: "When you pay utilities",
  },
  {
    id: 18,
    name: "Entertainment",
    amount: 18,
    color: "#00bcfe",
    subtext: "When you go to the cinema",
  },
  {
    id: 19,
    name: "Transportation",
    amount: 19,
    color: "#ff5345",
    subtext: "When you take a bus",
  },
  {
    id: 20,
    name: "Investments",
    amount: 20,
    color: "#ff6da8",
    subtext: "When you invest",
  },
];

export { cards };
